import "./globals.css";
import { Inter } from "next/font/google";
import { Russo_One } from "next/font/google";
import { Lexend } from "next/font/google";

import localFont from "next/font/local";


const inter = Inter({ subsets: ["latin"] });
const russo = Russo_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-russo_o",
});
const lexend = Lexend({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lexend",
});
const clockFont = localFont({
  src: "./fonts/alarm_clock.ttf",
  display: "swap",
  variable: "--font-clock",
});
export const metadata = {
  title: "24 hour wake",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${russo.variable} ${clockFont.variable} ${lexend.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
